// Mocks generated by Mockito 5.4.4 from annotations
// in powerca_mobile/test/features/work_diary/data/repositories/work_diary_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:powerca_mobile/features/work_diary/data/datasources/work_diary_remote_datasource.dart'
    as _i3;
import 'package:powerca_mobile/features/work_diary/data/models/work_diary_entry_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkDiaryEntryModel_0 extends _i1.SmartFake
    implements _i2.WorkDiaryEntryModel {
  _FakeWorkDiaryEntryModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkDiaryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkDiaryRemoteDataSource extends _i1.Mock
    implements _i3.WorkDiaryRemoteDataSource {
  MockWorkDiaryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.WorkDiaryEntryModel>> getEntriesByJob({
    required int? jobId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByJob,
          [],
          {
            #jobId: jobId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.WorkDiaryEntryModel>>.value(
            <_i2.WorkDiaryEntryModel>[]),
      ) as _i4.Future<List<_i2.WorkDiaryEntryModel>>);

  @override
  _i4.Future<List<_i2.WorkDiaryEntryModel>> getEntriesByStaff({
    required int? staffId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByStaff,
          [],
          {
            #staffId: staffId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.WorkDiaryEntryModel>>.value(
            <_i2.WorkDiaryEntryModel>[]),
      ) as _i4.Future<List<_i2.WorkDiaryEntryModel>>);

  @override
  _i4.Future<_i2.WorkDiaryEntryModel> getEntryById(int? wdId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryById,
          [wdId],
        ),
        returnValue: _i4.Future<_i2.WorkDiaryEntryModel>.value(
            _FakeWorkDiaryEntryModel_0(
          this,
          Invocation.method(
            #getEntryById,
            [wdId],
          ),
        )),
      ) as _i4.Future<_i2.WorkDiaryEntryModel>);

  @override
  _i4.Future<_i2.WorkDiaryEntryModel> addEntry(
          _i2.WorkDiaryEntryModel? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
        ),
        returnValue: _i4.Future<_i2.WorkDiaryEntryModel>.value(
            _FakeWorkDiaryEntryModel_0(
          this,
          Invocation.method(
            #addEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.WorkDiaryEntryModel>);

  @override
  _i4.Future<_i2.WorkDiaryEntryModel> updateEntry(
          _i2.WorkDiaryEntryModel? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i4.Future<_i2.WorkDiaryEntryModel>.value(
            _FakeWorkDiaryEntryModel_0(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.WorkDiaryEntryModel>);

  @override
  _i4.Future<void> deleteEntry(int? wdId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [wdId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<double> getTotalHoursByJob(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByJob,
          [jobId],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> getTotalHoursByStaff({
    required int? staffId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByStaff,
          [],
          {
            #staffId: staffId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);
}
