// Mocks generated by Mockito 5.4.4 from annotations
// in powerca_mobile/test/features/work_diary/domain/usecases/get_entries_by_job_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:powerca_mobile/core/errors/failures.dart' as _i5;
import 'package:powerca_mobile/features/work_diary/domain/entities/work_diary_entry.dart'
    as _i6;
import 'package:powerca_mobile/features/work_diary/domain/repositories/work_diary_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkDiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkDiaryRepository extends _i1.Mock
    implements _i3.WorkDiaryRepository {
  MockWorkDiaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>> getEntriesByJob({
    required int? jobId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByJob,
          [],
          {
            #jobId: jobId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkDiaryEntry>>(
          this,
          Invocation.method(
            #getEntriesByJob,
            [],
            {
              #jobId: jobId,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>> getEntriesByStaff({
    required int? staffId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByStaff,
          [],
          {
            #staffId: staffId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkDiaryEntry>>(
          this,
          Invocation.method(
            #getEntriesByStaff,
            [],
            {
              #staffId: staffId,
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkDiaryEntry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>> getEntryById(
          int? wdId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryById,
          [wdId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkDiaryEntry>(
          this,
          Invocation.method(
            #getEntryById,
            [wdId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>> addEntry(
          _i6.WorkDiaryEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkDiaryEntry>(
          this,
          Invocation.method(
            #addEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>> updateEntry(
          _i6.WorkDiaryEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkDiaryEntry>(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkDiaryEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteEntry(int? wdId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [wdId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteEntry,
            [wdId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalHoursByJob(int? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByJob,
          [jobId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalHoursByJob,
            [jobId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalHoursByStaff({
    required int? staffId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByStaff,
          [],
          {
            #staffId: staffId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalHoursByStaff,
            [],
            {
              #staffId: staffId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);
}
