// Mocks generated by Mockito 5.4.4 from annotations
// in powerca_mobile/test/features/leave_requests/domain/usecases/get_leave_requests_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:powerca_mobile/core/errors/failures.dart' as _i5;
import 'package:powerca_mobile/features/leave_requests/domain/entities/leave_request.dart'
    as _i6;
import 'package:powerca_mobile/features/leave_requests/domain/repositories/leave_request_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LeaveRequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveRequestRepository extends _i1.Mock
    implements _i3.LeaveRequestRepository {
  MockLeaveRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.LeaveRequest>>> getLeaveRequests({
    required int? staffId,
    String? status,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaveRequests,
          [],
          {
            #staffId: staffId,
            #status: status,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.LeaveRequest>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.LeaveRequest>>(
          this,
          Invocation.method(
            #getLeaveRequests,
            [],
            {
              #staffId: staffId,
              #status: status,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.LeaveRequest>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>> getLeaveRequestById(
          int? leaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaveRequestById,
          [leaId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>.value(
                _FakeEither_0<_i5.Failure, _i6.LeaveRequest>(
          this,
          Invocation.method(
            #getLeaveRequestById,
            [leaId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>> createLeaveRequest(
          _i6.LeaveRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLeaveRequest,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>.value(
                _FakeEither_0<_i5.Failure, _i6.LeaveRequest>(
          this,
          Invocation.method(
            #createLeaveRequest,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>> updateLeaveRequest(
          _i6.LeaveRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLeaveRequest,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>.value(
                _FakeEither_0<_i5.Failure, _i6.LeaveRequest>(
          this,
          Invocation.method(
            #updateLeaveRequest,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LeaveRequest>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelLeaveRequest(int? leaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelLeaveRequest,
          [leaId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelLeaveRequest,
            [leaId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>> getLeaveBalance(
          int? staffId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaveBalance,
          [staffId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, double>>(
          this,
          Invocation.method(
            #getLeaveBalance,
            [staffId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>>);
}
